version: '3.8'

networks:
  presto:
    ipam:
      config:
        - subnet: 10.18.0.0/24

services:
  coordinator:
    image: prestodb/presto:0.282
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.8'
          memory: 7.5G
        reservations:
          cpus: '1.2'
          memory: 6G
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/prestorials/docker-swarm/coordinator/config.properties:/opt/presto-server/etc/config.properties
      - /home/ubuntu/prestorials/docker-swarm/coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - /home/ubuntu/prestorials/docker-swarm/coordinator/node.properties:/opt/presto-server/etc/node.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      presto:

  worker_1:
    image: prestodb/presto:0.282
    restart: always
    depends_on:
      - coordinator
    deploy:
      resources:
        limits:
          cpus: '1.8'
          memory: 7.5G
        reservations:
          cpus: '1.2'
          memory: 6G
    volumes:
      - /home/ubuntu/prestorials/docker-swarm/workers/config.properties:/opt/presto-server/etc/config.properties
      - /home/ubuntu/prestorials/docker-swarm/workers/jvm.config:/opt/presto-server/etc/jvm.config
      - /home/ubuntu/prestorials/docker-swarm/workers/1/node.properties:/opt/presto-server/etc/node.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      presto:
  
  worker_2:
    image: prestodb/presto:0.282
    restart: always
    depends_on:
      - coordinator
    deploy:
      resources:
        limits:
          cpus: '1.8'
          memory: 7.5G
        reservations:
          cpus: '1.2'
          memory: 6G
    volumes:
      - /home/ubuntu/prestorials/docker-swarm/workers/config.properties:/opt/presto-server/etc/config.properties
      - /home/ubuntu/prestorials/docker-swarm/workers/jvm.config:/opt/presto-server/etc/jvm.config
      - /home/ubuntu/prestorials/docker-swarm/workers/2/node.properties:/opt/presto-server/etc/node.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
      - /home/ubuntu/prestorials/docker-swarm/catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      presto:

