version: '3.8'

networks:
  presto:
    ipam:
      config:
        - subnet: 10.18.0.0/24

services:
  coordinator:
    image: prestodb/presto:0.282
    restart: always
    deploy:
      resources:
        limits:
          cpus: '7'
          memory: 15G
        reservations:
          cpus: '7'
          memory: 15G
    ports:
      - 8080:8080
    volumes:
      - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./coordinator/node.properties:/opt/presto-server/etc/node.properties
      - ./catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
      - ./catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      presto:

  worker_1:
    image: prestodb/presto-native:0.283-dev
    restart: always
    depends_on:
      - coordinator
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '7'
          memory: 15G
        reservations:
          cpus: '7'
          memory: 15G
    volumes:
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/node_1.properties:/opt/presto-server/etc/node.properties
      - ./catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      presto:

  worker_2:
    image: prestodb/presto-native:0.283-dev
    restart: always
    depends_on:
      - coordinator
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '7'
          memory: 15G
        reservations:
          cpus: '7'
          memory: 15G
    volumes:
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/node_2.properties:/opt/presto-server/etc/node.properties
      - ./catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      presto:

  worker_3:
    image: prestodb/presto-native:0.283-dev
    restart: always
    depends_on:
      - coordinator
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '7'
          memory: 15G
        reservations:
          cpus: '7'
          memory: 15G
    volumes:
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/node_3.properties:/opt/presto-server/etc/node.properties
      - ./catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      presto:
